# SwornGuns Configuration
# This is mostly for realism features
# By dmulloy2

# Block break effect when entities are hit
# Defaults to redstone block
# guns-only: Do blood effect for only guns
blood-effect:
  enabled: true
  block-id: REDSTONE_BLOCK
  guns-only: false

# Smoke effect when entities are hit by a bullet
smoke-effect: true

# Sound made when an entity is hit by a bullet
# A list of valid sounds can be found here:
# http://jd.bukkit.org/rb/apidocs/org/bukkit/Sound.html
bullet-sound:
  enabled: true
  sound: entity.magma_cube.jump

# Blocks broken when shot
block-shatter:
  enabled: true
  blocks:
    - oak_leaves
    - glass
    - glass_pane
    - sand
    - gravel

# Crackable blocks crack when shot
block-crack: true

# Debug - only use this if you know what you're doing
debug: false

# Disabled Worlds
# Worlds guns will not fire in
disabledWorlds:

# Whether or not to update guns when a player changes worlds
# Useful for per-world permissions and stuff
updateGunsOnWorldChange: false