name: SwornGuns
main: net.dmulloy2.swornguns.SwornGuns
version: ${project.version}${project.build.number}
author: dmulloy2
description: Guns in Minecraft!
api-version: "1.13"
commands: 
  swornguns:
    description: SwornGuns root command
    usage: /<command> <args>
    aliases: [gun, guns]
permissions:
  swornguns.*:
    description: Allows access to all SwornGuns features
    default: op
    children:
      swornguns.reload: true
      swornguns.fire.*: true
  swornguns.reload:
    description: Allows access to '/gun reload'
    default: false
  swornguns.fire.*:
    description: Allows the firing of all guns
    default: op